baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'LSTeh, Luka Slapnik s.p.'

theme = 'PaperMod'

[params]
  defaultTheme = 'light'
  disableThemeToggle = true
  favicon = '/static/logo_transparent.ico'

[menu]
  [[menu.main]]
  name = "Domov"
  url = "/_index/"
  weight = 1
  
  [[menu.main]]
  name = "Storitve"
  url = "/storitve/"
  weight = 2

  [[menu.main]]
  name = "Reference"
  url = "/reference/"
  weight = 3

  [[menu.main]]
  name = "Kontakt"
  url = "/about/"
  weight = 4
